services:
  mongo:
    image: mongo:latest
    container_name: 467finalproj-mongo
    # ports:
    # - "3001:27017"
    restart: "unless-stopped"
    volumes:
      - "../data/scripts/467projdata.archive.gz:/restore/467projdata.archive.gz:ro"
      - "../data/scripts/mongo_restore.sh:/docker-entrypoint-initdb.d/mongo_restore.sh:ro"
    init: true
    cpu_percent: 5
    mem_limit: "0.5GiB"

  web:
    build: .
    container_name: 467finalproj-web
    # ports:
    #   - "3000:80"
    restart: "unless-stopped"
    depends_on:
      - mongo
    environment:
      NUXT_MONGO_URI: "mongodb://mongo:27017/467projdata"
    mem_limit: '1GiB'
    cpu_percent: 10
		read_only: true
    dns:
      - 1.1.1.1
      - 1.0.0.1